name: 'CRONOS Code Guard'
description: 'Static analysis for Python code changes with risk assessment'
author: 'cythonvijay'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_url:
    description: 'CRONOS API endpoint URL'
    required: true
  mode:
    description: 'Analysis mode: STRICT, BOUNDARY, or CONTRACT'
    required: false
    default: 'STRICT'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -qq
          sudo apt-get install -y jq curl
        fi

    - name: Run CRONOS Analysis
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        MODE: ${{ inputs.mode }}
      run: |
        set -eo pipefail

        API_URL="${API_URL%/}"
        REPORT_DIR="cronos-reports"
        mkdir -p "$REPORT_DIR"

        echo "Running CRONOS in $MODE mode"
        echo "API: $API_URL"

        # Health check
        if ! curl -sf --max-time 10 "$API_URL/" >/dev/null; then
          echo "API unreachable"
          exit 1
        fi

        # Detect changed Python files
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.py$' || true)
        else
          FILES=$(git ls-files '*.py' || true)
        fi

        if [ -z "$FILES" ]; then
          echo "No Python files changed"
          echo "## CRONOS: No changes detected" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        FAIL_COUNT=0
        WARN_COUNT=0
        PASS_COUNT=0

        for file in $FILES; do
          [ ! -f "$file" ] && continue

          echo "Analyzing: $file"

          OLD_CODE=""
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            OLD_CODE=$(git show HEAD~1:"$file" 2>/dev/null || echo "")
          fi

          NEW_CODE=$(cat "$file")

          PAYLOAD=$(jq -n \
            --arg old "$OLD_CODE" \
            --arg new "$NEW_CODE" \
            --arg mode "$MODE" \
            '{old_code:$old,new_code:$new,mode:$mode}')

          RESPONSE=$(curl -s -X POST "$API_URL/analyze_ci" \
            -H "Content-Type: application/json" \
            --max-time 60 \
            -d "$PAYLOAD")

          if [ -z "$RESPONSE" ]; then
            echo "Empty response from API"
            FAIL_COUNT=$((FAIL_COUNT+1))
            continue
          fi

          if ! echo "$RESPONSE" | jq empty >/dev/null 2>&1; then
            echo "Invalid JSON response"
            FAIL_COUNT=$((FAIL_COUNT+1))
            continue
          fi

          STATUS=$(echo "$RESPONSE" | jq -r '.status // "FAIL"')
          RISK=$(echo "$RESPONSE" | jq -r '.risk // 100')
          FINDINGS=$(echo "$RESPONSE" | jq -r '.findings_count // 0')

          echo "Status: $STATUS | Risk: $RISK | Findings: $FINDINGS"

          echo "$RESPONSE" > "$REPORT_DIR/$(echo "$file" | tr '/' '_').json"

          echo "### $file" >> "$GITHUB_STEP_SUMMARY"
          echo "- Status: $STATUS" >> "$GITHUB_STEP_SUMMARY"
          echo "- Risk: $RISK/100" >> "$GITHUB_STEP_SUMMARY"
          echo "- Findings: $FINDINGS" >> "$GITHUB_STEP_SUMMARY"

          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "#### Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "$RESPONSE" | jq -r '.summary[]?' | sed 's/^/- /' >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          case "$STATUS" in
            PASS) PASS_COUNT=$((PASS_COUNT+1));;
            WARN) WARN_COUNT=$((WARN_COUNT+1));;
            *) FAIL_COUNT=$((FAIL_COUNT+1));;
          esac
        done

        echo "## CRONOS Summary" >> "$GITHUB_STEP_SUMMARY"
        echo "- Passed: $PASS_COUNT" >> "$GITHUB_STEP_SUMMARY"
        echo "- Warned: $WARN_COUNT" >> "$GITHUB_STEP_SUMMARY"
        echo "- Failed: $FAIL_COUNT" >> "$GITHUB_STEP_SUMMARY"

        if [ "$FAIL_COUNT" -gt 0 ]; then
          exit 1
        fi
