name: "CRONOS Enterprise Intelligence"

description: >
  CRONOS Enterprise Code Intelligence Engine.
  Performs fast CI gate analysis and optional full AI intelligence analysis.

author: "CRONOS"

branding:
  icon: "shield"
  color: "purple"

inputs:

  api_url:
    description: "CRONOS API URL"
    required: true

  mode:
    description: "Analysis mode: STRICT, BOUNDARY, CONTRACT"
    required: true
    default: "STRICT"

  repo:
    description: "Repository name"
    required: false

  github_token:
    description: "GitHub token"
    required: false

  pr_number:
    description: "Pull request number"
    required: false

  post_pr_comment:
    description: "Post PR comment with intelligence"
    required: false
    default: "false"

  create_annotations:
    description: "Create GitHub annotations"
    required: false
    default: "true"

  fail_on_severity:
    description: "Fail threshold: CRITICAL, HIGH, MEDIUM, LOW, SAFE"
    required: false
    default: "HIGH"

  full_analysis:
    description: "Run full AI intelligence analysis"
    required: false
    default: "false"

runs:
  using: "composite"

  steps:

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq curl

    - name: Run CRONOS Intelligence
      shell: bash
      run: |
        set -euo pipefail

        API="${{ inputs.api_url }}"
        MODE="${{ inputs.mode }}"
        REPO="${{ inputs.repo }}"
        TOKEN="${{ inputs.github_token }}"
        PR="${{ inputs.pr_number }}"
        FULL="${{ inputs.full_analysis }}"
        FAIL_LEVEL="${{ inputs.fail_on_severity }}"

        mkdir -p cronos-reports

        echo "==========================================="
        echo "CRONOS v8 Enterprise Intelligence Engine"
        echo "Mode: $MODE"
        echo "Full Analysis: $FULL"
        echo "==========================================="

        FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.py$' || true)

        if [ -z "$FILES" ]; then
          echo "No Python files changed."
          exit 0
        fi

        FAIL=0

        for FILE in $FILES; do

          echo ""
          echo "Analyzing: $FILE"

          OLD=$(git show HEAD~1:$FILE 2>/dev/null || echo "")
          NEW=$(cat "$FILE")

          if [ "$FULL" = "true" ]; then

            RESPONSE=$(curl -s -X POST "$API/analyze_full" \
              -H "Content-Type: application/json" \
              -d "$(jq -n \
                --arg old "$OLD" \
                --arg new "$NEW" \
                --arg mode "$MODE" \
                --arg repo "$REPO" \
                --arg file "$FILE" \
                '{old_code:$old,new_code:$new,mode:$mode,repo:$repo,file:$file}')")

          else

            RESPONSE=$(curl -s -X POST "$API/analyze_ci" \
              -H "Content-Type: application/json" \
              -d "$(jq -n \
                --arg old "$OLD" \
                --arg new "$NEW" \
                --arg mode "$MODE" \
                '{old_code:$old,new_code:$new,mode:$mode}')")

          fi

          echo "$RESPONSE" > cronos-reports/$(basename $FILE).json

          STATUS=$(echo "$RESPONSE" | jq -r '.status')
          SEVERITY=$(echo "$RESPONSE" | jq -r '.severity')
          RISK=$(echo "$RESPONSE" | jq -r '.risk_score')

          echo "Status: $STATUS  Severity: $SEVERITY  Risk: $RISK"

          if [ "$SEVERITY" = "$FAIL_LEVEL" ] || \
             [ "$SEVERITY" = "CRITICAL" ]; then
              FAIL=1
          fi

          if [ "$FULL" = "true" ]; then

            REPORT_ID=$(echo "$RESPONSE" | jq -r '.report_id')

            if [ "$PR" != "null" ] && [ -n "$TOKEN" ]; then

              curl -s -X POST "$API/github/pr_comment" \
                -H "Content-Type: application/json" \
                -d "$(jq -n \
                  --arg id "$REPORT_ID" \
                  --arg pr "$PR" \
                  --arg repo "$REPO" \
                  --arg token "$TOKEN" \
                  '{report_id:$id,pr_number:($pr|tonumber),repo:$repo,github_token:$token}')"

            fi

          fi

        done

        if [ "$FAIL" = "1" ]; then
          echo ""
          echo "CRONOS detected HIGH risk changes"
          exit 1
        fi

        echo ""
        echo "CRONOS analysis passed"
