name: 'CRONOS Code Guard'
description: 'Static analysis for Python code changes with risk assessment'
author: 'cythonvijay'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_url:
    description: 'CRONOS API endpoint URL'
    required: true
  mode:
    description: 'Analysis mode: STRICT, BOUNDARY, or CONTRACT'
    required: false
    default: 'STRICT'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update -qq
          sudo apt-get install -y jq curl
        fi

    - name: Run CRONOS Analysis
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        MODE: ${{ inputs.mode }}
      run: |
        set -euo pipefail

        API_URL="${API_URL%/}"
        REPORT_DIR="cronos-reports"
        mkdir -p "$REPORT_DIR"

        echo "========================================"
        echo "CRONOS Code Analysis"
        echo "========================================"
        echo "API: $API_URL"
        echo "Mode: $MODE"
        echo "========================================"

        echo "Testing API connectivity..."
        if ! curl -sf --max-time 10 "$API_URL/" > /dev/null 2>&1; then
          echo "ERROR: Cannot reach API at $API_URL"
          echo "## CRONOS: API Unreachable" >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
        echo "API reachable OK"

        FILES=""
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.py$' || true)
        else
          FILES=$(git ls-files '*.py' || true)
        fi

        if [ -z "$FILES" ]; then
          echo "No Python files changed"
          echo "## CRONOS: No changes detected" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        echo "Files to analyze:"
        echo "$FILES"

        FAIL_COUNT=0
        WARN_COUNT=0
        PASS_COUNT=0
        TOTAL=0

        for file in $FILES; do
          [ ! -f "$file" ] && continue

          TOTAL=$((TOTAL + 1))
          echo "----------------------------------------"
          echo "File $TOTAL: $file"
          echo "----------------------------------------"

          OLD_FILE=$(mktemp /tmp/cronos_old_XXXXXX)
          NEW_FILE=$(mktemp /tmp/cronos_new_XXXXXX)
          PAYLOAD_FILE=$(mktemp /tmp/cronos_payload_XXXXXX)
          RESP_FILE=$(mktemp /tmp/cronos_resp_XXXXXX)

          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git show HEAD~1:"$file" > "$OLD_FILE" 2>/dev/null || printf "" > "$OLD_FILE"
          else
            printf "" > "$OLD_FILE"
          fi

          cat "$file" > "$NEW_FILE"

          python3 -c "
import json
with open('$OLD_FILE', 'r') as f:
    old_content = f.read()
with open('$NEW_FILE', 'r') as f:
    new_content = f.read()
payload = {'old_code': old_content, 'new_code': new_content, 'mode': '$MODE'}
with open('$PAYLOAD_FILE', 'w') as f:
    json.dump(payload, f)
print('Payload size: ' + str(len(json.dumps(payload))) + ' bytes')
"

          rm -f "$OLD_FILE" "$NEW_FILE"

          set +e
          HTTP_CODE=$(curl -s -w "%{http_code}" \
            -o "$RESP_FILE" \
            -X POST "$API_URL/analyze_ci" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            --max-time 60 \
            -d "@$PAYLOAD_FILE")
          CURL_EXIT=$?
          set -e

          rm -f "$PAYLOAD_FILE"

          echo "HTTP: $HTTP_CODE curl_exit: $CURL_EXIT"

          if [ "$CURL_EXIT" -ne 0 ]; then
            echo "FAIL: Network error"
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo '{"status":"FAIL","risk":100,"findings_count":1,"summary":["Network error"]}' > "$REPORT_DIR/${file//\//_}.json"
            rm -f "$RESP_FILE"
            continue
          fi

          if [ "$HTTP_CODE" != "200" ]; then
            echo "FAIL: HTTP $HTTP_CODE"
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo "{\"status\":\"FAIL\",\"risk\":100,\"findings_count\":1,\"summary\":[\"HTTP $HTTP_CODE\"]}" > "$REPORT_DIR/${file//\//_}.json"
            rm -f "$RESP_FILE"
            continue
          fi

          RESP_SIZE=$(wc -c < "$RESP_FILE" 2>/dev/null || echo 0)
          echo "Response size: $RESP_SIZE bytes"

          if [ "$RESP_SIZE" -eq 0 ]; then
            echo "FAIL: Empty response"
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo '{"status":"FAIL","risk":100,"findings_count":1,"summary":["Empty response"]}' > "$REPORT_DIR/${file//\//_}.json"
            rm -f "$RESP_FILE"
            continue
          fi

          if ! jq empty "$RESP_FILE" 2>/dev/null; then
            echo "FAIL: Invalid JSON"
            cat "$RESP_FILE" | head -3
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo '{"status":"FAIL","risk":100,"findings_count":1,"summary":["Invalid JSON"]}' > "$REPORT_DIR/${file//\//_}.json"
            rm -f "$RESP_FILE"
            continue
          fi

          STATUS=$(jq -r '.status // "FAIL"' "$RESP_FILE")
          RISK=$(jq -r '.risk // 100' "$RESP_FILE")
          FINDINGS=$(jq -r '.findings_count // 0' "$RESP_FILE")

          cp "$RESP_FILE" "$REPORT_DIR/${file//\//_}.json"
          rm -f "$RESP_FILE"

          echo "Status: $STATUS | Risk: $RISK/100 | Findings: $FINDINGS"

          {
            echo "### $file"
            echo "- **Status:** $STATUS"
            echo "- **Risk:** $RISK/100"
            echo "- **Findings:** $FINDINGS"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"

          case "$STATUS" in
            PASS) PASS_COUNT=$((PASS_COUNT + 1)); echo "PASS" ;;
            WARN) WARN_COUNT=$((WARN_COUNT + 1)); echo "WARN" ;;
            FAIL) FAIL_COUNT=$((FAIL_COUNT + 1)); echo "FAIL" ;;
            *)    FAIL_COUNT=$((FAIL_COUNT + 1)); echo "UNKNOWN: $STATUS" ;;
          esac

        done

        echo "========================================"
        echo "Total: $TOTAL | Passed: $PASS_COUNT | Warned: $WARN_COUNT | Failed: $FAIL_COUNT"
        echo "========================================"

        {
          echo "## CRONOS Analysis Summary"
          echo "- **Total:** $TOTAL"
          echo "- **Passed:** $PASS_COUNT"
          echo "- **Warnings:** $WARN_COUNT"
          echo "- **Failed:** $FAIL_COUNT"
        } >> "$GITHUB_STEP_SUMMARY"

        if [ "$FAIL_COUNT" -gt 0 ]; then
          echo "BUILD BLOCKED - $FAIL_COUNT file(s) failed"
          exit 1
        else
          echo "BUILD APPROVED"
          exit 0
        fi
