name: "CRONOS Code Guard"
description: "Reliable CI risk analysis for Python"

inputs:
  api_url:
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_url }}
