name: "CRONOS Code Guard"
description: "Static change-risk analysis using CRONOS API"
inputs:
  api_url:
    required: true
    description: "Base URL of CRONOS API (no trailing slash)"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_url }}
