name: "CRONOS Enterprise Intelligence"

description: >
  CRONOS Enterprise Code Intelligence Engine.
  Performs fast CI gate analysis and full AI intelligence analysis.

author: "CRONOS"

branding:
  icon: "shield"
  color: "purple"

inputs:

  api_url:
    required: true

  mode:
    required: true
    default: "STRICT"

  repo:
    required: false

  github_token:
    required: false

  pr_number:
    required: false

  post_pr_comment:
    required: false
    default: "false"

  create_annotations:
    required: false
    default: "true"

  fail_on_severity:
    required: false
    default: "HIGH"

  full_analysis:
    required: false
    default: "false"

runs:
  using: "composite"

  steps:

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq curl

    - name: Run CRONOS Enterprise Intelligence
      shell: bash
      run: |

        set -eo pipefail

        API="${{ inputs.api_url }}"
        MODE="${{ inputs.mode }}"
        REPO="${{ inputs.repo }}"
        TOKEN="${{ inputs.github_token }}"
        PR="${{ inputs.pr_number }}"
        FULL="${{ inputs.full_analysis }}"
        FAIL_LEVEL="${{ inputs.fail_on_severity }}"
        CREATE_ANNOT="${{ inputs.create_annotations }}"
        POST_COMMENT="${{ inputs.post_pr_comment }}"

        mkdir -p cronos-reports

        echo ""
        echo "=============================================="
        echo "CRONOS v8 Enterprise Intelligence Engine"
        echo "Mode: $MODE"
        echo "Full Analysis: $FULL"
        echo "Repository: $REPO"
        echo "=============================================="

        FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.py$' || true)

        if [ -z "$FILES" ]; then
          echo "No Python files changed."
          exit 0
        fi

        FAIL=0

        for FILE in $FILES; do

          echo ""
          echo "Analyzing: $FILE"

          OLD=$(git show HEAD~1:$FILE 2>/dev/null || echo "")
          NEW=$(cat "$FILE")

          if [ "$FULL" = "true" ]; then

            RESPONSE=$(curl -s -X POST "$API/analyze_full" \
              -H "Content-Type: application/json" \
              -d "$(jq -n \
                --arg old "$OLD" \
                --arg new "$NEW" \
                --arg mode "$MODE" \
                --arg repo "$REPO" \
                --arg file "$FILE" \
                '{old_code:$old,new_code:$new,mode:$mode,repo:$repo,file:$file}')")

          else

            RESPONSE=$(curl -s -X POST "$API/analyze_ci" \
              -H "Content-Type: application/json" \
              -d "$(jq -n \
                --arg old "$OLD" \
                --arg new "$NEW" \
                --arg mode "$MODE" \
                '{old_code:$old,new_code:$new,mode:$mode}')")

          fi


          echo "$RESPONSE" > cronos-reports/$(basename $FILE).json

          STATUS=$(echo "$RESPONSE" | jq -r '.status')
          SEVERITY=$(echo "$RESPONSE" | jq -r '.severity')
          RISK=$(echo "$RESPONSE" | jq -r '.risk_score')

          TECH=$(echo "$RESPONSE" | jq -r '.technical_explanation // empty')
          HUMAN=$(echo "$RESPONSE" | jq -r '.human_explanation // empty')
          REASON=$(echo "$RESPONSE" | jq -r '.risk_reasoning // empty')
          IMPACT=$(echo "$RESPONSE" | jq -r '.behavioral_impact // empty')

          echo ""
          echo "Result:"
          echo "Status   : $STATUS"
          echo "Severity : $SEVERITY"
          echo "Risk     : $RISK"


          # PRINT AI EXPLANATION (THIS WAS MISSING)
          if [ "$FULL" = "true" ]; then

            echo ""
            echo "Technical Explanation:"
            echo "$TECH"

            echo ""
            echo "Human Explanation:"
            echo "$HUMAN"

            echo ""
            echo "Risk Reasoning:"
            echo "$REASON"

            echo ""
            echo "Behavior Impact:"
            echo "$IMPACT"

          fi


          # CREATE ANNOTATIONS
          if [ "$CREATE_ANNOT" = "true" ] && [ "$STATUS" = "FAIL" ]; then

            echo "::error file=$FILE,title=CRONOS Intelligence::$HUMAN"

          fi


          # POST PR COMMENT
          if [ "$FULL" = "true" ] && \
             [ "$POST_COMMENT" = "true" ] && \
             [ "$PR" != "" ] && \
             [ "$TOKEN" != "" ]; then

            REPORT_ID=$(echo "$RESPONSE" | jq -r '.report_id')

            curl -s -X POST "$API/github/pr_comment" \
              -H "Content-Type: application/json" \
              -d "$(jq -n \
                --arg id "$REPORT_ID" \
                --arg pr "$PR" \
                --arg repo "$REPO" \
                --arg token "$TOKEN" \
                '{report_id:$id,pr_number:($pr|tonumber),repo:$repo,github_token:$token}')"

          fi


          # FAIL GATE
          if [ "$SEVERITY" = "$FAIL_LEVEL" ] || \
             [ "$SEVERITY" = "CRITICAL" ]; then
              FAIL=1
          fi

        done


        if [ "$FAIL" = "1" ]; then
          echo ""
          echo "CRONOS detected HIGH risk change"
          exit 1
        fi


        echo ""
        echo "CRONOS analysis passed"
